/* Interface Gráfica 1: Propriedades de um círculo */

package Nov_13;

import POO1.Circulo;


public class JanelaCirculo extends javax.swing.JFrame {
    
    /**
     * Creates new form Propriedades_Circulo
     */
    public JanelaCirculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbRaio = new javax.swing.JLabel();
        btDiametro = new javax.swing.JButton();
        btArea = new javax.swing.JButton();
        btPerimetro = new javax.swing.JButton();
        btVolume = new javax.swing.JButton();
        tfRaio = new javax.swing.JTextField();
        spResultado = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        btLimpar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Propriedades do Círculo");
        setResizable(false);

        lbRaio.setText("Raio:");

        btDiametro.setText("Diâmetro");
        btDiametro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDiametroActionPerformed(evt);
            }
        });

        btArea.setText("Área");
        btArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAreaActionPerformed(evt);
            }
        });

        btPerimetro.setText("Perímetro");
        btPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPerimetroActionPerformed(evt);
            }
        });

        btVolume.setText("Volume");
        btVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolumeActionPerformed(evt);
            }
        });

        tfRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRaioActionPerformed(evt);
            }
        });

        taResult.setColumns(20);
        taResult.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        taResult.setRows(5);
        spResultado.setViewportView(taResult);

        btLimpar.setForeground(new java.awt.Color(0, 0, 255));
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btFechar.setForeground(new java.awt.Color(255, 0, 0));
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spResultado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btDiametro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPerimetro)
                        .addGap(18, 18, 18)
                        .addComponent(btVolume))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRaio)
                        .addGap(4, 4, 4)
                        .addComponent(tfRaio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRaio)
                    .addComponent(tfRaio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDiametro)
                    .addComponent(btArea)
                    .addComponent(btPerimetro)
                    .addComponent(btVolume))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btFechar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        taResult.setText("");
    }//GEN-LAST:event_btLimparActionPerformed

    private void btDiametroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDiametroActionPerformed
        try {
        Circulo circulo = new Circulo(Double.parseDouble(tfRaio.getText()));
        taResult.append("raio = " +  String.format("%.2f", circulo.getRaio()) + ", diâmetro = " + String.format("%.2f", circulo.diametro()) + "\n");
        taResult.append("-----------------------------------------------\n");
        }
        catch(NumberFormatException erro){
            taResult.append("Entrada inválida! Tente novamente." + "\n");
    }//GEN-LAST:event_btDiametroActionPerformed
    }
    private void tfRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRaioActionPerformed
        try {
        Circulo circulo = new Circulo(Double.parseDouble(tfRaio.getText()));
        taResult.append("raio = " +  String.format("%.2f", circulo.getRaio()) + "\n");
        taResult.append("-----------------------------------------------\n");
        }
        catch(NumberFormatException erro){
            taResult.append("Entrada inválida! Tente novamente." + "\n");
             
        }
    }//GEN-LAST:event_tfRaioActionPerformed

    private void btAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAreaActionPerformed
        try {
        Circulo circulo = new Circulo(Double.parseDouble(tfRaio.getText()));
        taResult.append("raio = " +  String.format("%.2f", circulo.getRaio()) + ", área = " + String.format("%.2f", circulo.area()) + "\n");
        taResult.append("-----------------------------------------------\n");
        }
        catch(NumberFormatException erro){
            taResult.append("Entrada inválida! Tente novamente." + "\n");
        }
    }//GEN-LAST:event_btAreaActionPerformed

    private void btPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPerimetroActionPerformed
        try {
        Circulo circulo = new Circulo(Double.parseDouble(tfRaio.getText()));
        taResult.append("raio = " +  String.format("%.2f", circulo.getRaio()) + ", perímetro = " + String.format("%.2f", circulo.perimetro()) + "\n");
        taResult.append("-----------------------------------------------\n");
        }
        catch(NumberFormatException erro){
            taResult.append("Entrada inválida! Tente novamente." + "\n");
        }
    }//GEN-LAST:event_btPerimetroActionPerformed

    private void btVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolumeActionPerformed
        try {
        Circulo circulo = new Circulo(Double.parseDouble(tfRaio.getText()));
        taResult.append("raio = " +  String.format("%.2f", circulo.getRaio()) + ", volume = " + String.format("%.2f", circulo.volume()) + "\n");
        taResult.append("-----------------------------------------------\n");
        }
        catch(NumberFormatException erro){
            taResult.append("Entrada inválida! Tente novamente." + "\n");
        }
    }//GEN-LAST:event_btVolumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaCirculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaCirculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaCirculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaCirculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaCirculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btArea;
    private javax.swing.JButton btDiametro;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPerimetro;
    private javax.swing.JButton btVolume;
    private javax.swing.JLabel lbRaio;
    private javax.swing.JScrollPane spResultado;
    private javax.swing.JTextArea taResult;
    private javax.swing.JTextField tfRaio;
    // End of variables declaration//GEN-END:variables
}
