/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nov_17;
import POO1.Circulo;

public class JanelaCirculo extends javax.swing.JInternalFrame {
    public JanelaCirculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btImprimir = new javax.swing.JButton();
        tfRaio = new javax.swing.JTextField();
        lbRaio = new javax.swing.JLabel();
        btLimpar = new javax.swing.JButton();
        spResultado = new javax.swing.JScrollPane();
        result = new javax.swing.JTextArea();

        setClosable(true);
        setResizable(true);
        setTitle("Propriedades do círculo");
        setAlignmentX(0.0F);
        setAlignmentY(0.0F);

        btImprimir.setText("Imprimir");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        tfRaio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRaioActionPerformed(evt);
            }
        });

        lbRaio.setText("Raio:");

        btLimpar.setText("Limpar");
        btLimpar.setAlignmentY(0.0F);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        result.setColumns(20);
        result.setRows(5);
        spResultado.setViewportView(result);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbRaio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btImprimir)
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(spResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btImprimir)
                    .addComponent(tfRaio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbRaio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(btLimpar)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(spResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfRaioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRaioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfRaioActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
    try{
        result.setText("");
    
        double raio = Double.parseDouble(tfRaio.getText());
   
        Circulo circulo = new Circulo(raio);
    
        result.append(String.format("Raio: %.2f\n", circulo.getRaio()));
        result.append("------------------------------------------------------\n");
        result.append(String.format("Diâmetro: %.2f\n", circulo.diametro()));
        result.append("------------------------------------------------------\n");
        result.append(String.format("Perímetro: %.2f\n", circulo.perimetro()));
        result.append("------------------------------------------------------\n");
        result.append(String.format("Área: %.2f\n", circulo.area()));
        result.append("------------------------------------------------------\n");
        result.append(String.format("Volume: %.2f\n", circulo.volume()));
        result.append("------------------------------------------------------\n");
    }
    catch(NumberFormatException erro){
        result.append("Entrada Inválida!"+ "\n");
    }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
       result.setText("");
    }//GEN-LAST:event_btLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JLabel lbRaio;
    private javax.swing.JTextArea result;
    private javax.swing.JScrollPane spResultado;
    private javax.swing.JTextField tfRaio;
    // End of variables declaration//GEN-END:variables
}
